import { 
  Aperture, 
  Camera, 
  Compass, 
  Cpu, 
  Eye, 
  Focus, 
  Globe, 
  Image as ImageIcon, 
  Layers, 
  Moon, 
  Mountain, 
  Settings, 
  Sun, 
  ThermometerSnowflake,
  Video
} from 'lucide-react';
import { CalibrationFrame, Discipline, GearCategory, WorkflowStep } from './types';

export const DISCIPLINES: Discipline[] = [
  {
    id: 'wide-field',
    title: 'Wide-Field Nightscapes',
    description: 'Capturing the Milky Way arc over terrestrial landscapes.',
    details: [
      'Combines landscape photography with astrophotography.',
      'Often requires single exposures or simple stacking.',
      'Emphasis on composition and foreground interest.'
    ],
    icon: Mountain,
    image: 'https://picsum.photos/800/600?grayscale&blur=2' // Placeholder
  },
  {
    id: 'dso',
    title: 'Deep-Sky Objects (DSO)',
    description: 'Imaging nebulae, galaxies, and star clusters beyond our solar system.',
    details: [
      'Requires integration times of hours or even days.',
      'Essential usage of cooled sensors to reduce thermal noise.',
      'Heavily reliant on precise tracking mounts.'
    ],
    icon: Globe,
    image: 'https://picsum.photos/800/601?grayscale&blur=2'
  },
  {
    id: 'planetary',
    title: 'Planetary Imaging',
    description: 'High-magnification capture of planets, the moon, and the sun.',
    details: [
      'Utilizes "Lucky Imaging" technique.',
      'Shoots high-speed video to beat atmospheric turbulence.',
      'Selects only the sharpest frames for stacking.'
    ],
    icon: Moon,
    image: 'https://picsum.photos/800/602?grayscale&blur=2'
  }
];

export const GEAR_CATEGORIES: GearCategory[] = [
  {
    id: 'mounts',
    label: 'Mounts & Tracking',
    title: 'The Foundation: Fighting Rotation',
    content: 'Counteracting Earth\'s rotation (15° per hour) is the single most critical factor in astrophotography.',
    comparison: [
      {
        label: 'Star Trackers',
        description: 'Portable, battery-powered units like the Sky-Watcher Star Adventurer. Ideal for wide-field and lightweight setups.'
      },
      {
        label: 'EQ Mounts',
        description: 'Heavy-duty Equatorial mounts (e.g., HEQ5). Essential for long focal lengths and heavy telescopes to eliminate field rotation.'
      }
    ]
  },
  {
    id: 'cameras',
    label: 'Sensors',
    title: 'Photon Collectors',
    content: 'The choice between convenience and raw performance.',
    comparison: [
      {
        label: 'Uncooled DSLR/Mirrorless',
        description: 'Versatile, easy to use, self-contained. Prone to thermal noise in long exposures during summer.'
      },
      {
        label: 'Cooled Astronomy Cameras',
        description: 'Dedicated sensors with TEC cooling. Maintains setpoint (e.g., -45°C below ambient) for massive thermal stability and repeatable calibration.'
      }
    ]
  },
  {
    id: 'optics',
    label: 'Optics',
    title: 'Glass & Aperture',
    content: 'Light gathering power is defined by the f-ratio, not just focal length.',
    comparison: [
      {
        label: 'Fast Aperture',
        description: 'Lenses with f/1.4 - f/2.8 are preferred to gather maximum light in short exposures.'
      },
      {
        label: 'The NPF Rule',
        description: 'Superior to the "500 Rule". Formula: (35 × Aperture + 30 × Pixel Pitch) ÷ Focal Length = Max Shutter Speed.'
      }
    ],
    technicalNote: 'Calculation ensures point-stars without trailing on high-resolution sensors.'
  }
];

export const CALIBRATION_FRAMES: CalibrationFrame[] = [
  {
    id: 'lights',
    title: 'Light Frames',
    description: 'The actual image data containing the signal (photons) from the object.',
    method: 'Capture as much total integration time as possible to increase Signal-to-Noise Ratio (SNR).',
    icon: ImageIcon
  },
  {
    id: 'darks',
    title: 'Dark Frames',
    description: 'Removes thermal noise generated by the sensor heat.',
    method: 'Lens cap ON. Same temperature, ISO/Gain, and exposure time as Light frames.',
    icon: ThermometerSnowflake
  },
  {
    id: 'flats',
    title: 'Flat Frames',
    description: 'Corrects optical vignetting and shadows from dust motes on the sensor.',
    method: 'Evenly illuminated light source. Histogram peak at ~50%. Focus must remain untouched.',
    icon: Sun
  },
  {
    id: 'bias',
    title: 'Bias Frames',
    description: 'Removes the electronic readout noise inherent to the sensor.',
    method: 'Lens cap ON. Shortest possible shutter speed (e.g., 1/4000s or 1/8000s).',
    icon: Cpu
  }
];

export const WORKFLOW_STEPS: WorkflowStep[] = [
  {
    id: 'planning',
    title: 'Planning',
    description: 'Analyzing the Bortle Scale (light pollution), moon phase, and target altitude using tools like Stellarium.',
    icon: Compass,
    color: 'text-blue-400'
  },
  {
    id: 'capture',
    title: 'Data Acquisition',
    description: 'Executing the imaging plan. Ensuring perfect focus (Bahtinov mask) and guiding accuracy.',
    icon: Camera,
    color: 'text-cyan-400'
  },
  {
    id: 'stacking',
    title: 'Stacking',
    description: 'Aligning and averaging sub-exposures to mathematically reject noise and outliers (satellites/planes).',
    icon: Layers,
    color: 'text-purple-400'
  },
  {
    id: 'processing',
    title: 'Post-Processing',
    description: 'Stretching the non-linear data (histogram manipulation), color calibration, and star reduction.',
    icon: Settings,
    color: 'text-fuchsia-400'
  }
];
